#!/bin/sh

BUILD_TYPE=${BUILD_TYPE:-RelWithDebInfo}
RELOADABLE=${RELOADABLE:-ON}

if [ "${RELOADABLE}" = "ON" ]
then
	SUFFIX="reloadable"
else
	SUFFIX="static"
fi

BUILD_DIR=".build/${BUILD_TYPE}-${SUFFIX}"

mkdir -p ${BUILD_DIR}
cd ${BUILD_DIR}

if [ ! -f build.ninja ]
then
	cmake \
		-G "Ninja" \
		-DCMAKE_TOOLCHAIN_FILE=../../cmake/linux.cmake \
		-DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
		-DRELOADABLE="${RELOADABLE}" \
		-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
		../../
fi

cmake --build .
