#!/bin/sh

BUILD_TYPE=${BUILD_TYPE:-RelWithDebInfo}
RELOADABLE=${RELOADABLE:-ON}

if [ "${RELOADABLE}" = "ON" ]
then
	SUFFIX="reloadable"
else
	SUFFIX="static"
fi

BUILD_DIR="${BUILD_TYPE}-${SUFFIX}"

mkdir -p .build
cd .build

if [ ! -f "${BUILD_DIR}/build.ninja" ]
then
	cmake \
		-G "Ninja" \
		-B ${BUILD_DIR} \
		-DCMAKE_TOOLCHAIN_FILE=../../cmake/linux.cmake \
		-DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
		-DRELOADABLE="${RELOADABLE}" \
		-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
		../
fi

cmake --build ${BUILD_DIR}
